name: Purge jsDelivr Cache
on:
  push:
    branches:
      - main
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cache
        run: |
          curl -i https://purge.jsdelivr.net/gh/shrik7891-pixel/ptv@main/userScript.js
          curl -i https://purge.jsdelivr.net/gh/shrik7891-pixel/ptv@main/tv_feed.json
          curl -i https://purge.jsdelivr.net/gh/shrik7891-pixel/ptv@main/topics.json
